# Generated by Django 4.1 on 2022-11-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='onsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=b'I01\n')),
                ('weight', models.FloatField()),
                ('breakfast', models.TimeField()),
                ('lunch', models.TimeField()),
                ('dinner', models.TimeField()),
                ('snack', models.CharField(blank=b'I01\n', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesname', models.CharField(max_length=150, unique=b'I01\n')),
                ('scientificname', models.CharField(max_length=150, unique=b'I01\n')),
                ('healthyweightmin', models.FloatField()),
                ('healthyweightmax', models.FloatField()),
                ('origin', models.CharField(max_length=150)),
                ('land', models.BooleanField()),
            ],
        ),
    ]
