# Generated by Django 4.1 on 2022-11-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ottApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onsite",
            name="age",
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onsite",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="F", max_length=1
            ),
            preserve_default=False,
        ),
    ]
