# Generated by Django 4.1 on 2022-11-07 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ottApp", "0002_onsite_age_onsite_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="onsite",
            name="species",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="ottApp.species",
            ),
            preserve_default=False,
        ),
    ]
